'use client';
import {useEffect} from 'react';
import {Camera,ShieldCheck,Sparkles} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {useCamera} from './use-camera';
export function CameraPanel({target,onComplete,autoStart=false}:{target?:string;onComplete:()=>void;autoStart?:boolean}){
 const camera=useCamera(target||'',onComplete);
 useEffect(()=>{if(autoStart)void camera.start()},[]);
 const moving=camera.isBody||target==='letter-J'||target==='letter-Z';
 return <div className="camera-column"><div className="camera-stage"><video ref={camera.video} width={640} height={480} muted autoPlay playsInline className={camera.status==='live'?'visible':''}/><canvas ref={camera.canvas} className={camera.status==='live'?'visible':''}/><div className="camera-top"><span><i className={camera.status==='live'?'status-dot on':'status-dot'}/>{camera.status==='live'?'CAMERA LIVE':camera.status==='loading'?'STARTING CAMERA':'CAMERA OFF'}</span><span>{moving?'MOVEMENT CHALLENGE':'HANDSHAPE CHALLENGE'}</span></div>{camera.status!=='live'&&<div className="camera-empty"><div className="camera-icon"><Camera size={32}/></div><h3>Your stage is ready.</h3><p>{camera.isBody?'Show your face, shoulders, and both hands. Perform the complete sign.':moving?'Match the handshape, then trace the complete movement.':'Match the reference. Hold your sign steady.'}</p><button className="primary" onClick={camera.start} disabled={camera.status==='loading'||camera.checking}><Camera size={17}/>{camera.status==='loading'?'Getting ready…':'Enable camera'}</button><small><ShieldCheck size={14}/>Video stays on your device</small></div>}{camera.status==='live'&&<button className="pause" onClick={camera.stop}>Pause camera</button>}<div className="camera-bottom"><span>{camera.tracking}</span><span>Good light helps</span></div></div><div className="camera-feedback"><Sparkles size={20}/><p role="status">{camera.feedback}</p></div>{target?<><Progress value={camera.hold} aria-label="Hold your sign"/><p className="fine-print">{moving?'Perform the complete sign.':'Hold the matching shape for 1.5 seconds.'} Experimental reference matching; facial grammar is not graded.</p></>:<p className="fine-print">Guided practice: the camera is a mirror here. Movement, facial expression, and two-handed signs are not automatically graded.</p>}<Dialog><DialogTrigger className="camera-help text-button">Camera help</DialogTrigger><DialogContent className="lesson-dialog"><DialogTitle>Camera help & tracker check</DialogTitle><p>Use even light. For letters, keep your whole hand in frame. For words, step back until your face, shoulders, and both hands are visible. Match the demonstrated version. This experimental checker can miss valid signs; its result is not an assessment of fluency.</p><button className="text-button" onClick={camera.test} disabled={camera.status==='live'||camera.status==='loading'||camera.checking}>{camera.checking?'Checking video input…':'Check tracker without a webcam'}</button><p role="status">{camera.check}</p></DialogContent></Dialog></div>
}
