import mediaData from './media.json';
export type Media={src:string;kind:string;source:string;original?:string;animated?:boolean};
export type Card={id:string;label:string;type:'sign'|'concept'|'conversation';description:string;steps:string[];tip:string;source:string;media?:Media;camera?:string;sequence?:string[];question:{prompt:string;choices:string[];answer:number;explanation:string}};
export type Unit={id:string;title:string;subtitle:string;icon:string;minutes:number;cards:string[];takeaway:string};
const abc='https://www.lifeprint.com/asl101/fingerspelling/abc.htm';
const grammar='https://www.lifeprint.com/asl101/pages-layout/grammar.htm';
const media=mediaData as Record<string,Media>;
const alphabetDescriptions:Record<string,string>={
A:'Make a closed fist with your thumb resting alongside the index finger.',B:'Hold four fingers straight and together. Fold your thumb across your palm.',C:'Curve your fingers and thumb into an open C shape.',D:'Point your index finger up. Curve the other fingertips to meet your thumb.',E:'Bend all four fingers so the fingertips sit close to your thumb. Keep the hand relaxed.',F:'Touch the tips of your thumb and index finger. Extend the other three fingers.',G:'Point your index finger and thumb sideways, parallel to each other. Fold the other fingers.',H:'Extend your index and middle fingers together, pointing sideways.',I:'Raise your pinky. Fold the other fingers and rest the thumb across them.',J:'Begin with an I handshape. Move your pinky to trace the curve of a J.',K:'Extend your index and middle fingers apart, with the thumb between them touching the middle finger.',L:'Point your index finger up and your thumb sideways. Fold the remaining three fingers.',M:'Close your hand with the thumb tucked under the index, middle, and ring fingers.',N:'Close your hand with the thumb tucked under the index and middle fingers.',O:'Curve all fingertips toward your thumb to make a rounded O.',P:'Use the K handshape with the hand tilted downward.',Q:'Use the G handshape with your index finger and thumb directed downward.',R:'Cross your index and middle fingers. Fold the remaining fingers.',S:'Make a fist with the thumb across the front of your fingers.',T:'Tuck your thumb between the index and middle fingers of a closed hand.',U:'Extend your index and middle fingers straight up and together.',V:'Extend your index and middle fingers, separated. Hold the other two down with the thumb.',W:'Extend your index, middle, and ring fingers. Hold your pinky down with the thumb.',X:'Curl your index finger into a hook. Fold the other fingers.',Y:'Extend your thumb and pinky. Curl the other three fingers into your palm.',Z:'Extend your index finger and draw a Z in the air: across, diagonally back, and across again.'};
const alphabetCards:Card[]=Object.entries(alphabetDescriptions).map(([letter,description])=>({id:`letter-${letter}`,label:letter,type:'sign',description,steps:[description,['G','H','P','Q'].includes(letter)?'Check the sideways or downward orientation in the photograph.':`Keep the hand at a comfortable shoulder height.${['J','Z'].includes(letter)?' The photo shows the handshape; the letter also needs movement.':''}`],tip:['J','Z'].includes(letter)?'This letter moves. Follow the demonstrated movement. Left-handed signers mirror the right-handed version.':letter==='L'?'Think of two straight sides of a small L.':letter==='Y'?'Only the thumb and pinky extend.':letter==='I'?'Keep the thumb tucked; only your pinky points up.':letter==='V'?'Leave a clear gap between your two raised fingers.':'Compare handshape, palm direction, and thumb placement. There is no need to squeeze.',source:abc,media:{src:`/references/${letter.toLowerCase()}.jpg`,kind:'image',source:abc},camera:`letter-${letter}`,question:{prompt:`Which description matches the letter ${letter}?`,choices:[description,'Spread all five fingers and wave.','Place two flat hands on your shoulders.'],answer:0,explanation:description}}));
const vocabRows:[string,string,string,string,string][]=[
['hello','Hello','Give a natural, relaxed wave toward the person you are greeting.','Keep your hand visible and your expression friendly.','A greeting starts by getting the other person’s visual attention.'],
['thankyou','Thank you','Bring a flat hand near your lips, then move it forward toward the person you are thanking.','Let the hand travel outward and slightly down.','Watch the direction of the movement, not just the handshape.'],
['please','Please','Place a flat hand over your chest and move it in a small circle.','Use one hand and a gentle, natural motion.','Facial expression also communicates politeness. PLEASE is not needed in every request.'],
['sorry','Sorry','Make an A handshape and move it in a small circle against your chest.','Keep the thumb along the side of your fist.','Notice the closed hand here compared with the flat hand in PLEASE.'],
['yes','Yes','Make a fist and bend it at the wrist as if it is nodding.','Keep the movement small and clear.','Your expression should fit what you mean; the hand alone is not the whole message.'],
['no','No','Bring your index and middle fingers together toward your thumb.','Watch the short closing movement in the demonstration.','A short double movement can be polite; a firm single movement can be more emphatic.'],
['my','My','Place your flat dominant hand on your chest.','Keep the fingers together and use a relaxed contact.','MY uses a flat hand. Pointing to yourself communicates I or ME.'],
['you','You','Point your index finger toward the person you are addressing.','Use a relaxed, clear pointing movement.','Pointing is an ordinary part of ASL pronouns.'],
['name','Name','Extend the index and middle fingers together on both hands. Cross and tap the dominant pair on top of the other pair.','Watch the orientation and the brief double contact.','NAME often uses two taps, though natural signing includes variation.'],
['what','What','Hold relaxed open hands palm-up and move them slightly outward.','Furrow your eyebrows for the question.','A question’s facial expression matters as much as its hands.'],
['nice','Nice','Brush your flat dominant hand across the upturned palm of your other hand.','Keep the motion smooth and brief.','This hand movement can also mean CLEAN; context changes the meaning.'],
['meet','Meet','Hold both index fingers upright and bring the hands toward each other.','Keep the fingertips pointing upward rather than touching tip to tip.','The direction of MEET can show who is meeting whom.'],
['mother','Mother','Spread your fingers and touch the thumb near your chin.','Watch the light contact and open handshape.','The lower face location distinguishes MOTHER from FATHER.'],
['father','Father','Spread your fingers and touch the thumb near your forehead.','Use the same open handshape as MOTHER.','Location is part of a sign’s meaning.'],
['friend','Friend','Hook the index fingers together, then switch which hand is on top and hook again.','Watch both contacts in the demonstration.','Use both hands. Do not mistake this for fingerspelling F.'],
['want','Want','Hold open hands in front of you with palms up. Pull them toward yourself while gently curling the fingers.','Keep both hands at about waist-to-chest height.','The inward motion is an essential part of WANT.'],
['water','Water','Make a W handshape and tap the index-finger side near your lips twice.','Keep three fingers raised, with your pinky held down.','The location and tapping distinguish WATER from the letter W.'],
['help','Help','Rest a thumb-up fist on your other open palm, then lift both hands together.','Let the base hand support the fist.','HELP is directional. This lesson starts with the neutral form.'],
['again','Again','Curve your dominant hand at the knuckles. Move its fingertips in an arc into your open opposite palm.','Watch the forward curve and contact.','AGAIN is useful when you want a signer to repeat something.'],
['slow','Slow','Move the palm of your dominant hand a short distance up the back of your other hand and forearm.','Keep the contact light.','Use the normal form in the demonstration when asking for a slower pace.'],
['understand','Understand','Start with a loosely closed hand near your forehead. Flick the index finger up.','Think of an idea becoming clear.','Add a negative headshake to express not understanding.'],
['learn','Learn','Gather your fingertips from your open opposite palm and bring them toward your forehead.','Watch the hand close as it moves upward.','Compare the demonstration’s starting position and endpoint.'],
['deaf','Deaf','Touch the cheek near your ear, then near the corner of your mouth, using an index finger.','Stay on the cheek rather than touching the ear or lips themselves.','Some signers reverse the order. Deaf identities and language preferences vary.'],
['hearing','Hearing','Hold an index finger near your mouth and make a small forward circular movement.','Watch the repeated rotation near the mouth.','This means a hearing person in this context, not simply the physical ability to hear.']];
const vocabCards:Card[]=vocabRows.map(([id,label,description,step,tip],index)=>({id,label,type:'sign',description,steps:[description,step],tip,source:media[id].source,media:media[id],question:{prompt:`Which instruction matches ${label.toUpperCase()}?`,choices:[description,vocabRows[(index+1)%vocabRows.length][2],vocabRows[(index+3)%vocabRows.length][2]],answer:0,explanation:tip}}));
const numberInstructions=['Raise your index finger.','Raise your index and middle fingers.','Raise your thumb, index, and middle fingers.','Raise all four fingers and tuck your thumb.','Spread all five fingers.','Touch your thumb to your pinky; extend the other three fingers.','Touch your thumb to your ring finger; extend the other three fingers.','Touch your thumb to your middle finger; extend the other three fingers.','Touch your thumb to your index finger; extend the other three fingers.','Make a thumb-up fist and shake it gently.'];
const numberCards:Card[]=numberInstructions.map((description,i)=>({id:`number-${i+1}`,label:String(i+1),type:'sign',description,steps:[description,i<5?'For these isolated counting forms, orient your palm toward yourself.':'Check palm orientation in the demonstration.'],tip:i<5?'Numbers 1–5 typically face inward when signed alone. Palm orientation can change in other contexts.':i===9?'Ten includes movement. A still thumb-up pose alone is not the whole sign.':'For 6–9, the fingertip touching your thumb changes the number.',source:media[`number-${i+1}`].source,media:media[`number-${i+1}`],question:{prompt:`How is the number ${i+1} formed?`,choices:[description,numberInstructions[(i+3)%10],numberInstructions[(i+6)%10]],answer:0,explanation:description}}));
function concept(id:string,label:string,description:string,steps:string[],tip:string,choices:string[],answer:number,source=grammar):Card{return {id,label,type:'concept',description,steps,tip,source,question:{prompt:label+': check your understanding',choices,answer,explanation:tip}}}
const concepts:Card[]=[
concept('welcome','A visual language','ASL is a language with its own grammar. Fingerspelling is one part of it, not a replacement for signing.', ['Choose a comfortable dominant hand and stay consistent.','Keep your hands visible in front of your body.','Relax your shoulders and take breaks if your hands feel tired.'],'Meaning comes from handshape, location, movement, palm direction, and facial expression.',['ASL is English represented one letter at a time.','ASL has its own grammar and uses the face and body as well as the hands.','All countries use the same sign language.'],1),
concept('attention','Start with visual attention','Before signing, make sure the other person is looking at you.', ['Use a small wave in their field of view.','Face your conversation partner and keep your hands visible.','Follow the person’s preferred way of communicating.'],'Learn alongside Deaf teachers and fluent signers; an app cannot replace a conversation.',['Start signing while the other person looks away.','Get visual attention, then begin.','Assume every Deaf person prefers the same communication method.'],1,'https://www.lifeprint.com/asl101/pages-signs/h/hello.htm'),
concept('fingerspell','Spell with a steady rhythm','Use fingerspelling for names and words when it is appropriate. Practice slowly enough to make each handshape clear.', ['Keep your hand near shoulder height.','Avoid bouncing your entire arm between letters.','Try A-N-A, S-A-M, then your own name.'],'Start smoothly and clearly. Speed comes later.',['Bounce your whole arm for every letter.','Prioritize speed over clarity.','Keep a steady hand position and make each letter clear.'],2,abc),
concept('questions','Your face asks the question','In a yes/no question, raised eyebrows are common. In a what, who, or where question, eyebrows are generally furrowed.', ['Practice YOU DEAF? with raised eyebrows.','Practice NAME YOU? with furrowed eyebrows.','Keep looking at your conversation partner.'],'The question type changes the expression. These are beginner patterns; real usage has nuance.',['Keep the same neutral face for every question.','Use raised eyebrows for yes/no and generally furrowed brows for WH questions.','Always sign a separate question mark.'],1),
concept('negation','Say what you do not understand','A negative headshake can change the meaning of a sign such as UNDERSTAND.', ['Practice UNDERSTAND with a neutral or affirmative expression.','Repeat with a negative headshake for DON’T UNDERSTAND.','Follow with AGAIN or SLOW when you need help.'],'ASL does not translate English word by word. Negation can be expressed through the head and face.',['Add a negative headshake to UNDERSTAND.','Spell the letters N-O before every sign.','Keep your face still and only sign faster.'],0,'https://www.lifeprint.com/asl101/pages-signs/u/understand.htm'),
concept('word-order','Build meaning, not word-for-word English','Simple ASL sentences often use a subject, verb, and object. Other orders can emphasize a topic; there is no single order for every sentence.', ['Practice a simple request using WANT and WATER.','Notice that ASL does not require a sign for every English word.','Treat uppercase sign labels as practice notes, not an exact writing system for ASL.'],'Word order, facial expression, and context work together. Avoid learning one sentence formula as a universal rule.',['ASL must always put every object first.','ASL follows English word for word.','ASL has multiple sentence patterns and uses expression and context.'],2),
concept('next-steps','Take it into a real conversation','You have a foundation to keep practicing: an alphabet, numbers, everyday vocabulary, and simple exchanges.', ['Introduce yourself to a willing practice partner.','Ask for repetition rather than guessing.','Continue with an introductory class led by a Deaf teacher or qualified ASL instructor.'],'Finishing this course records practice, not a certification of fluency.',['Course completion means certified fluency.','Keep learning with Deaf teachers and real conversation.','You no longer need demonstrations or feedback.'],1)
];
const conversations:Card[]=[
{id:'introduce',label:'Introduce yourself',type:'conversation',description:'Greet someone, say your name, and ask theirs.',steps:['HELLO.','MY NAME + fingerspell your name.','NAME YOU? Use a questioning expression with furrowed eyebrows.'],sequence:['hello','my','name','name','you'],tip:'This is a scaffold for practice. The final NAME YOU? asks the other person’s name. Use a WH-question expression.',source:media.name.source,question:{prompt:'Which expression fits asking someone’s name?',choices:['Furrowed eyebrows for a WH question.','A negative headshake throughout.','No eye contact.'],answer:0,explanation:'A name question asks for information rather than yes/no, so use a WH-question expression.'}},
{id:'nice-to-meet',label:'Nice to meet you',type:'conversation',description:'Use two signs to welcome a new acquaintance.',steps:['Sign NICE.','Sign MEET, directing the movement toward the other person.','Keep a friendly, natural expression.'],sequence:['nice','meet'],tip:'Directional movement can carry information about “me” and “you.” You do not need one sign for every English word.',source:media.meet.source,question:{prompt:'What can the direction of MEET communicate?',choices:['Who is meeting whom.','The spelling of someone’s name.','Nothing; direction never matters.'],answer:0,explanation:'MEET is directional. Its movement can communicate who is meeting whom.'}},
{id:'request-water',label:'Ask for water',type:'conversation',description:'Put your everyday signs into a short request.',steps:['Sign WANT, then WATER.','Add PLEASE if it fits your request and expression.','When someone helps, sign THANK YOU.'],sequence:['want','water','please','thankyou'],tip:'Use facial expression and context. A polite request is more than adding the sign PLEASE.',source:media.please.source,question:{prompt:'After someone brings you water, which sign fits?',choices:['THANK YOU','NAME','DEAF'],answer:0,explanation:'THANK YOU acknowledges the person’s help.'}},
{id:'repair',label:'Keep a conversation going',type:'conversation',description:'It is normal to miss something. Ask the other signer to repeat or slow down.',steps:['Sign UNDERSTAND with a negative headshake.','Ask AGAIN.','Use SLOW if you need a gentler pace.'],sequence:['understand','again','slow'],tip:'Let the other person know what you need instead of pretending to understand.',source:media.understand.source,question:{prompt:'What is a useful response when you miss a sign?',choices:['Pretend you understood.','Ask for repetition or a slower pace.','End every conversation immediately.'],answer:1,explanation:'AGAIN and SLOW help you participate while you are learning.'}}
];
export const cards:Card[]=[...alphabetCards,...numberCards,...vocabCards,...concepts,...conversations].map(card=>({...card,camera:card.type==='concept'?undefined:card.id}));
export const byId=Object.fromEntries(cards.map(card=>[card.id,card])) as Record<string,Card>;
export const units:Unit[]=[
{id:'foundations',title:'Meet your hands',subtitle:'Your first four signs',icon:'hand',minutes:8,cards:['welcome','letter-L','letter-Y','letter-I','letter-V','attention'],takeaway:'Make four distinct handshapes and begin with visual attention.'},
{id:'alphabet-one',title:'The alphabet · A–M',subtitle:'Build your fingerspelling toolkit',icon:'letters',minutes:16,cards:'ABCDEFGHIJKLM'.split('').map(x=>'letter-'+x),takeaway:'Recognize and practice the first half of the alphabet.'},
{id:'alphabet-two',title:'The alphabet · N–Z',subtitle:'From handshapes to your name',icon:'letters',minutes:18,cards:[...'NOPQRSTUVWXYZ'.split('').map(x=>'letter-'+x),'fingerspell'],takeaway:'Finish the alphabet and fingerspell a short name with a steady rhythm.'},
{id:'numbers',title:'Make it count',subtitle:'Numbers one through ten',icon:'numbers',minutes:12,cards:Array.from({length:10},(_,i)=>'number-'+(i+1)),takeaway:'Recognize 1–10 and notice how palm orientation affects number signs.'},
{id:'essentials',title:'Everyday kindness',subtitle:'Greetings, thanks, and responses',icon:'heart',minutes:10,cards:['hello','thankyou','please','sorry','yes','no'],takeaway:'Greet someone, thank them, apologize, and respond yes or no.'},
{id:'introductions',title:'Let’s get acquainted',subtitle:'Names and a first exchange',icon:'people',minutes:14,cards:['my','you','name','what','nice','meet','introduce','nice-to-meet'],takeaway:'Introduce yourself, ask a name, and welcome someone.'},
{id:'everyday',title:'People & everyday needs',subtitle:'Family, friends, and simple requests',icon:'home',minutes:12,cards:['mother','father','friend','want','water','help','request-water'],takeaway:'Talk about a few people in your life and make a simple request.'},
{id:'conversation',title:'Keep the conversation going',subtitle:'Questions, expression, and repair',icon:'chat',minutes:18,cards:['again','slow','understand','learn','deaf','hearing','questions','negation','word-order','repair','next-steps'],takeaway:'Use expressions, ask for repetition, and prepare for further beginner study.'}
];
export const totalMinutes=units.reduce((sum,u)=>sum+u.minutes,0);
export function lookupLesson(query:string,current?:Card):{text:string;source:string}{
 const q=query.toLowerCase().trim();
 if(!q)return {text:'Ask about a letter, number, everyday sign, camera setup, or an ASL sentence.',source:abc};
 if(/camera|detect|outline|tracker|webcam/.test(q))return {text:'Letters and numbers compare your hand to reference shapes; J, Z, and 10 also require movement. Everyday signs compare handshape, body location, and motion. Step back to show your face, shoulders, and both hands for those lessons. Matching is experimental and may reject valid variations. Facial grammar is not graded. Pause the camera to run the tracker check.',source:abc};
 if(/privacy|record|save|upload/.test(q))return {text:'Camera frames stay in your browser and are not recorded or uploaded by this app. Course progress is stored in this browser. YouTube demonstrations load only when you choose to watch them.',source:abc};
 const letter=q.match(/(?:letter|sign)\s+([a-z])\b/)?.[1];
 const number=q.match(/(?:number|count)\s+(10|[1-9])\b/)?.[1];
 let match=letter?byId['letter-'+letter.toUpperCase()]:number?byId['number-'+number]:undefined;
 if(!match){const words=q.match(/[a-z]+/g)||[];match=cards.filter(c=>c.label.length>1).map(c=>({card:c,score:words.reduce((n,w)=>n+(w.length>2&&c.label.toLowerCase().includes(w)?3:0),0)})).sort((a,b)=>b.score-a.score)[0]?.card; if(!match||!words.some(w=>w.length>2&&match!.label.toLowerCase().includes(w)))match=undefined;}
 if(!match&&/this|hint|help|how/.test(q))match=current;
 return match?{text:match.steps.join(' ')+' '+match.tip,source:match.source}:{text:'My local lesson library covers the alphabet, numbers 1–10, everyday signs, introductions, and beginner grammar. Try “How do I sign THANK YOU?” or “Explain questions.” I do not invent answers outside these lessons.',source:abc};
}
