'use client';
import {useEffect,useState,useMemo,useRef} from 'react';
import {Hand,BookOpen,ArrowRight,ArrowLeft,ArrowUpRight,Check,CheckCircle2,Flame,Zap,MessageCircle,Sparkles,Search,RotateCcw,Trophy,Camera,Library,GraduationCap,Home as HomeIcon,Hash,Heart,Users,ShieldCheck,Download} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Dialog,DialogTrigger,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {cards,byId,units,totalMinutes,lookupLesson,type Card,type Unit} from './course';
import {initialProgress,parseProgress,completeCard,reviewCard,dayKey,streak,unitCompleted,type ProgressState} from './progress';
import {Demonstration} from './demonstration';
import {CameraPanel} from './camera-panel';
import {Quiz} from './quiz';
import {ThemeToggle} from './theme-toggle';
const icons:Record<string,typeof Hand>={hand:Hand,letters:BookOpen,numbers:Hash,heart:Heart,people:Users,home:HomeIcon,chat:MessageCircle};
function CourseNavigation({progress,unitId,onSelect}:{progress:ProgressState;unitId:string;onSelect:(id:string)=>void}){
 const {setOpenMobile}=useSidebar();
 const today=Object.values(progress.completed).filter(x=>dayKey(new Date(x.at))===dayKey()).length;
 return <Sidebar className="course-sidebar"><SidebarHeader><a className="brand" href="/"><span><Hand size={25}/></span>signsprout<span className="brand-dot">.</span></a><p className="sidebar-caption">A NEW WAY TO CONNECT</p></SidebarHeader><SidebarContent><div className="path-heading"><BookOpen size={17}/><span>Your learning path</span></div><SidebarMenu>{units.map((unit,i)=>{const Icon=icons[unit.icon],done=unitCompleted(progress,unit.id),count=unit.cards.filter(id=>progress.completed[id]).length;return <SidebarMenuItem key={unit.id}><SidebarMenuButton className="unit-button" isActive={unit.id===unitId} onClick={()=>{onSelect(unit.id);setOpenMobile(false)}}><span className="unit-icon">{done?<Check size={19}/>:<Icon size={19}/>}</span><span><small>UNIT {String(i+1).padStart(2,'0')}</small><b>{unit.title}</b><em>{done?'Unit complete':`${count} / ${unit.cards.length} practiced`}</em></span>{unit.id===unitId&&<span className="selected-dot"/>}</SidebarMenuButton></SidebarMenuItem>})}</SidebarMenu></SidebarContent><SidebarFooter><div className="daily"><div><Sparkles size={20}/><b>A little every day.</b></div><p>Practice 4 new cards today.</p><Progress value={Math.min(today/4*100,100)} aria-label="Daily practice goal"/><small>{Math.min(today,4)} of 4 practiced today</small></div><span className="device-note"><ShieldCheck size={13}/>Your progress stays on this device</span></SidebarFooter></Sidebar>
}
function StudyCard({card,done,onComplete}:{card:Card;done:boolean;onComplete:(method:'camera'|'self'|'read')=>void}){
 const [sequenceIndex,setSequenceIndex]=useState(0),[sequencePassed,setSequencePassed]=useState<number[]>([]);
 const shown=card.type==='conversation'&&card.sequence?byId[card.sequence[sequenceIndex]]:card;
 function cameraComplete(){if(!card.sequence){onComplete('camera');return;}const passed=[...new Set([...sequencePassed,sequenceIndex])];setSequencePassed(passed);if(passed.length===card.sequence.length)onComplete('camera');else setSequenceIndex(card.sequence.findIndex((_,i)=>!passed.includes(i)));}
 return <><div className={'study-grid '+(card.type==='concept'?'concept-grid':'')}><div className="lesson-reference"><span className="eyebrow">{card.type==='concept'?'A LITTLE CONTEXT':card.type==='conversation'?'PUT IT TOGETHER':card.id.startsWith('letter-')?'LET’S SIGN THE LETTER':card.id.startsWith('number-')?'LET’S SIGN THE NUMBER':'LET’S LEARN A SIGN'}</span><h2 className={card.label.length<3?'large-label':''}>{card.label}</h2>{card.type==='conversation'&&card.sequence&&<div className="sequence-nav" aria-label="Conversation signs">{card.sequence.map((id,i)=><button key={id+i} onClick={()=>setSequenceIndex(i)} disabled={i>sequencePassed.length} aria-pressed={i===sequenceIndex}>{sequencePassed.includes(i)&&<Check size={11}/>} {byId[id].label}</button>)}</div>}{shown.media&&<Demonstration key={shown.id} card={shown}/>}<p className="reference-description">{card.type==='conversation'?shown.description:card.description}</p>{!shown.media&&<a className="source-link" href={card.source} target="_blank" rel="noreferrer">ASL University reference <ArrowUpRight size={14}/></a>}</div>{card.type==='concept'?<div className="concept-panel"><span className="concept-symbol"><BookOpen size={36}/></span><h3>Try this before you move on.</h3><ol>{card.steps.map(step=><li key={step}>{step}</li>)}</ol><div className="learning-note"><Sparkles size={20}/><p>{card.tip}</p></div></div>:<CameraPanel key={shown.id} target={shown.camera} autoStart={sequencePassed.length>0} onComplete={cameraComplete}/>}</div><div className="practice-complete"><Dialog><DialogTrigger className="secondary"><BookOpen size={16}/>Tips & instructions</DialogTrigger><DialogContent className="lesson-dialog"><DialogTitle>{card.label} · Your signing guide</DialogTitle><ol>{card.steps.map(step=><li key={step}>{step}</li>)}</ol><div className="learning-note"><Sparkles size={20}/><p>{card.tip}</p></div><LessonGuide current={card}/></DialogContent></Dialog>{done?<span className="success-label"><CheckCircle2 size={18}/>{card.camera?'Reference matched':'Practice complete'}</span>:card.camera?<span className="fine-print">Match the sign to unlock Next</span>:<button className="primary" onClick={()=>onComplete(card.type==='concept'?'read':'self')}><Check size={17}/>{card.type==='concept'?'Mark as read':'I practiced this sign'}</button>}</div></>

}
function LessonGuide({current}:{current:Card}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[reply,setReply]=useState<{text:string;source:string}|null>(null);
 return <section className="guide-wrap"><button className="guide-toggle" onClick={()=>setOpen(!open)} aria-expanded={open}><span><MessageCircle size={20}/><b>A question along the way?</b><small>Your local lesson guide can help.</small></span><span>{open?'Close':'Ask the guide'}<ArrowUpRight size={16}/></span></button>{open&&<div className="guide"><p>Answers come from this course’s reference library. No chat account or cloud AI is required.</p><div className="suggestions">{['Help with this sign','Camera setup','Explain questions'].map(q=><button key={q} onClick={()=>{setQuery(q);setReply(lookupLesson(q,current))}}>{q}</button>)}</div><form onSubmit={e=>{e.preventDefault();setReply(lookupLesson(query,current))}}><input aria-label="Question for the lesson guide" value={query} maxLength={300} onChange={e=>setQuery(e.target.value)} placeholder="How do I sign THANK YOU?"/><button className="primary" disabled={!query.trim()}>Ask<ArrowRight size={16}/></button></form>{reply&&<div className="guide-answer" role="status"><p>{reply.text}</p><a href={reply.source} target="_blank" rel="noreferrer">Open the lesson source <ArrowUpRight size={13}/></a></div>}</div>}</section>
}
export default function Page(){
 const [progress,setProgress]=useState<ProgressState>(initialProgress),[loaded,setLoaded]=useState(false),[storageError,setStorageError]=useState(false),[tab,setTab]=useState('learn'),[quiz,setQuiz]=useState(false),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[libraryCard,setLibraryCard]=useState<string|null>(null),[reviewIndex,setReviewIndex]=useState(0),[revealed,setRevealed]=useState(false),[reviewAll,setReviewAll]=useState(false),[reviewed,setReviewed]=useState<string[]>([]);
 const [verified,setVerified]=useState<string|null>(null);
 const progressRef=useRef(progress);progressRef.current=progress;
 useEffect(()=>{try{setProgress(parseProgress(localStorage.getItem('signsprout-course-v2'),localStorage.getItem('signsprout-progress')))}catch{setStorageError(true)}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('signsprout-course-v2',JSON.stringify(progress))}catch{setStorageError(true)}},[progress,loaded]);
 const unit=units.find(u=>u.id===progress.unit)||units[0],index=Math.min(progress.index,unit.cards.length-1),card=byId[unit.cards[index]],unitNumber=units.indexOf(unit)+1;
 const completedCount=Object.keys(progress.completed).length,completedUnits=units.filter(u=>unitCompleted(progress,u.id)).length,xp=completedCount*25+Object.values(progress.quizzes).filter(s=>s>=80).length*50;
 function selectUnit(id:string){setProgress(p=>({...p,unit:id,index:0}));setQuiz(false);setTab('learn');setLibraryCard(null)}
 useEffect(()=>{setVerified(null)},[card.id,tab,quiz,unit.id,libraryCard]);
 const canAdvance=card.camera?verified===card.id:!!progress.completed[card.id];
 function mark(method:'camera'|'self'|'read'){if(card.camera&&method!=='camera')return;if(method==='camera')setVerified(card.id);setProgress(p=>completeCard(p,card.id,method))}
 const filtered=cards.filter(c=>c.type==='sign'&&(category==='all'||category==='letters'&&c.id.startsWith('letter-')||category==='numbers'&&c.id.startsWith('number-')||category==='words'&&!c.id.startsWith('letter-')&&!c.id.startsWith('number-'))&&(c.label.toLowerCase().includes(search.toLowerCase())||c.description.toLowerCase().includes(search.toLowerCase())));
 const reviewPool=useMemo(()=>cards.filter(c=>progress.completed[c.id]&&(reviewAll||!progress.reviews[c.id]||progress.reviews[c.id].due<=dayKey())&&!reviewed.includes(c.id)),[progress.completed,progress.reviews,reviewAll,reviewed]);
 const review=reviewPool[Math.min(reviewIndex,Math.max(0,reviewPool.length-1))];
 function rate(correct:boolean){if(!review)return;setProgress(p=>reviewCard(p,review.id,correct));setReviewed(p=>[...p,review.id]);setRevealed(false);setReviewIndex(0)}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'read_sign_course',description:'Read the current lesson, automatic scoring support, and course progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');const p=progressRef.current,u=units.find(u=>u.id===p.unit)!;const c=byId[u.cards[p.index]];return {unit:u.title,lesson:c.label,instructions:c.steps,cameraScored:!!c.camera,practiced:Object.keys(p.completed).length,unitsCompleted:units.filter(u=>unitCompleted(p,u.id)).length}}},{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[]);
 function exportProgress(){const blob=new Blob([JSON.stringify(progress,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='signsprout-progress.json';a.click();URL.revokeObjectURL(url)}
 return <SidebarProvider><CourseNavigation progress={progress} unitId={unit.id} onSelect={selectUnit}/><SidebarInset className="main-surface"><Tabs value={tab} onValueChange={value=>{setTab(String(value));setLibraryCard(null);setQuiz(false)}}><header className="app-header"><div className="header-left"><SidebarTrigger className="mobile-menu"/><span>YOUR FIRST CONVERSATION STARTS HERE</span></div><div className="stats"><ThemeToggle/><span><Flame size={19}/><b>{streak(progress.days)}</b><small>day streak</small></span><span><Zap size={19}/><b>{xp}</b><small>XP</small></span><span className="avatar">You</span></div></header><div className={'workspace '+(tab==='learn'&&!quiz?'focus-mode':'')}><div className="intro"><div><p className="eyebrow">FROM FIRST SIGNS TO EVERYDAY CONNECTIONS</p><h1>{completedUnits===units.length?'Look how far you’ve come.':'A little practice. A new way to connect.'}</h1><p>{units.length} units · {cards.length} learning cards · start from wherever you are.</p></div><span className="level-badge"><GraduationCap size={18}/>BEGINNER FOUNDATIONS</span></div><TabsList className="main-tabs" variant="line"><TabsTrigger value="learn"><BookOpen size={17}/>Learn</TabsTrigger><TabsTrigger value="library"><Library size={17}/>Sign library</TabsTrigger><TabsTrigger value="review"><RotateCcw size={17}/>Review</TabsTrigger><TabsTrigger value="progress"><Trophy size={17}/>Your progress</TabsTrigger></TabsList>{storageError&&<p className="error-note" role="status">Browser storage is unavailable. You can keep practicing, but progress may not survive a reload. Export it from Your progress.</p>}
<TabsContent value="learn">{quiz?<Quiz key={unit.id} unit={unit} onNextUnit={unitNumber<units.length?()=>selectUnit(units[unitNumber].id):undefined} onViewProgress={()=>{setQuiz(false);setTab('progress')}} onBack={()=>setQuiz(false)} onFinish={score=>setProgress(p=>({...p,quizzes:{...p.quizzes,[unit.id]:Math.max(p.quizzes[unit.id]||0,score)},days:[...new Set([...p.days,dayKey()])]}))}/>:<section className="practice"><div className="practice-title"><div><span className="pill">UNIT {String(unitNumber).padStart(2,'0')} · {unit.minutes} MIN</span><h2>{unit.title}</h2><p>{unit.subtitle}</p></div><div className="unit-summary"><span>{unit.cards.filter(id=>progress.completed[id]).length} / {unit.cards.length}</span><small>cards practiced</small></div></div><div className="card-path" aria-label="Practice cards in this unit">{unit.cards.map((id,i)=><button key={id} title={byId[id].label} aria-label={`${i+1}. ${byId[id].label}${progress.completed[id]?', practiced':''}`} aria-current={i===index?'step':undefined} className={i===index?'active':progress.completed[id]?'done':''} onClick={()=>setProgress(p=>({...p,index:i}))}>{progress.completed[id]?<Check size={14}/>:i+1}</button>)}</div><StudyCard key={card.id} card={card} done={card.camera?verified===card.id:!!progress.completed[card.id]} onComplete={mark}/><div className="lesson-navigation"><button className="secondary" disabled={index===0} onClick={()=>setProgress(p=>({...p,index:Math.max(0,p.index-1)}))}><ArrowLeft size={16}/>Previous</button><span>Card {index+1} of {unit.cards.length}</span><button className="primary next-button" disabled={!canAdvance} title={canAdvance?'Continue':card.camera?'Correctly hold this sign in the camera to continue':'Complete this lesson to continue'} onClick={()=>{if(!canAdvance)return;index===unit.cards.length-1?setQuiz(true):setProgress(p=>({...p,index:p.index+1}))}}>{index===unit.cards.length-1?'Take checkpoint':'Next card'}<ArrowRight size={16}/></button></div><div className="unit-footer"><p><b>You’ll be able to:</b> {unit.takeaway}</p><button className="text-button" onClick={()=>setQuiz(true)}>{(progress.quizzes[unit.id]||0)>=80?'Retake checkpoint':'Try the unit checkpoint'}</button></div>{unitCompleted(progress,unit.id)&&<div className="unit-celebration"><Trophy/><div><h3>Unit complete. One step closer.</h3><p>Practice and checkpoint finished. Your next unit is ready.</p></div><button className="primary" onClick={()=>unitNumber<units.length?selectUnit(units[unitNumber].id):setTab('progress')}>{unitNumber<units.length?'Next unit':'See your progress'}<ArrowRight size={16}/></button></div>}</section>}</TabsContent>
<TabsContent value="library">{libraryCard?<section className="practice library-detail"><button className="text-button" onClick={()=>setLibraryCard(null)}><ArrowLeft size={16}/>Back to sign library</button><StudyCard key={libraryCard} card={byId[libraryCard]} done={byId[libraryCard].camera?verified===libraryCard:!!progress.completed[libraryCard]} onComplete={method=>{if(method==='camera')setVerified(libraryCard);setProgress(p=>completeCard(p,libraryCard,method))}}/></section>:<section className="library-section"><div className="section-heading"><div><h2>A sign for every small step.</h2><p>Find a handshape, replay a demonstration, or revisit something familiar.</p></div><span>{filtered.length} signs</span></div><div className="library-tools"><label className="search"><Search size={18}/><input aria-label="Search the sign library" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search signs, letters, or numbers…"/></label><div className="filters">{[['all','All signs'],['letters','Alphabet'],['numbers','Numbers'],['words','Everyday signs']].map(([value,label])=><button key={value} onClick={()=>setCategory(value)} aria-pressed={category===value}>{label}</button>)}</div></div><div className="library-grid">{filtered.map(c=><button className="library-tile" key={c.id} onClick={()=>setLibraryCard(c.id)}>{c.id.startsWith('letter-')?<img src={c.media!.src} alt={`ASL ${c.label}`} loading="lazy"/>:<span className="word-icon">{c.id.startsWith('number-')?<Hash/>:<Hand/>}</span>}<div><b>{c.label}</b><small>{c.camera?'Camera challenge':c.id.startsWith('letter-')?'Fingerspelling':c.id.startsWith('number-')?'Numbers':'Watch & practice'}</small></div>{progress.completed[c.id]?<CheckCircle2 size={17}/>:<ArrowUpRight size={17}/>}</button>)}</div>{!filtered.length&&<div className="empty"><Search/><h3>No matching signs.</h3><p>Try a shorter word, or browse all signs.</p><button className="secondary" onClick={()=>{setSearch('');setCategory('all')}}>Clear search</button></div>}</section>}</TabsContent>
<TabsContent value="review"><section className="review-section"><div className="section-heading"><div><h2>Make yesterday’s signs stick.</h2><p>Recall first, then reveal. Reviews return after 1, 2, 4, 8, and 14 days.</p></div><span>{reviewed.length} reviewed this session</span></div>{review?<div className="review-card"><span className="pill">{reviewAll?'PRACTICE REVIEW':'DUE TODAY'} · {reviewPool.length} REMAINING</span><h2>{revealed?review.label:review.type==='sign'?'Can you recall this sign?':'Explain this in your own words.'}</h2>{review.type==='sign'?<><div className="recall-prompt">{review.label}</div><p>Try signing it before you reveal the demonstration.</p></>:<div className="recall-prompt concept-recall">{review.label}</div>}{revealed?<><div className="review-reveal">{review.media&&<Demonstration key={review.id} card={review}/>}<p>{review.description}</p><p>{review.tip}</p></div><div className="button-row"><button className="secondary" onClick={()=>rate(false)}>Still learning</button><button className="primary" onClick={()=>rate(true)}><Check size={17}/>Remembered it</button></div></>:<button className="primary" onClick={()=>setRevealed(true)}>Reveal the answer <ArrowRight size={16}/></button>}</div>:<div className="empty"><CheckCircle2 size={40}/><h3>{completedCount?'You’re all caught up.':'Your review deck starts here.'}</h3><p>{completedCount?'Come back tomorrow, or revisit all your practiced cards now.':'Practice a few cards in Learn and they’ll appear in your review deck.'}</p><button className="primary" onClick={()=>completedCount?(setReviewAll(true),setReviewed([]),setReviewIndex(0)):setTab('learn')}>{completedCount?'Review practiced cards':'Start learning'}<ArrowRight size={16}/></button></div>}</section></TabsContent>
<TabsContent value="progress"><section className="progress-section"><div className="section-heading"><div><h2>Every small win adds up.</h2><p>Your course progress, saved on this device.</p></div><button className="secondary" onClick={exportProgress}><Download size={16}/>Export progress</button></div><div className="progress-stats"><article><Trophy/><b>{completedUnits}<small> / {units.length}</small></b><span>units completed</span></article><article><Hand/><b>{completedCount}<small> / {cards.length}</small></b><span>cards practiced</span></article><article><Flame/><b>{streak(progress.days)}</b><span>day streak</span></article><article><Zap/><b>{xp}</b><span>XP earned</span></article></div><div className="progress-units">{units.map((u,i)=>{const count=u.cards.filter(id=>progress.completed[id]).length;return <article key={u.id}><span className="progress-number">{unitCompleted(progress,u.id)?<Check/>:String(i+1).padStart(2,'0')}</span><div><h3>{u.title}</h3><Progress value={count/u.cards.length*100} aria-label={`${u.title} practice progress`}/><p>{count}/{u.cards.length} cards · Checkpoint: {progress.quizzes[u.id]===undefined?'not taken':`${progress.quizzes[u.id]}%`}</p></div><button className="text-button" onClick={()=>selectUnit(u.id)}>{unitCompleted(progress,u.id)?'Revisit':'Continue'}<ArrowRight size={16}/></button></article>})}</div><div className="learning-note"><GraduationCap/><p>About {totalMinutes} minutes of introductory material, plus practice. Finishing records your learning activity; it is not a fluency certificate. Keep building with Deaf teachers and real conversation.</p></div></section></TabsContent><footer className="app-footer"><span>Small wins. Meaningful connections.</span><a href="https://www.lifeprint.com/asl101/lessons/lessons.htm" target="_blank" rel="noreferrer">Continue learning with ASL University <ArrowUpRight size={13}/></a></footer></div></Tabs></SidebarInset></SidebarProvider>
}
